POST http://localhost:8080/Personenbefoerderung HTTP/1.1
Content-Type: application/json

{
  "user_ID": 1,
  "anzahlPersonen": 4,
  "preis": 300,
  "ang_ges": 1,
  "start": "Gießen",
  "ziel": "Hamburg",
  "beschreibung": "TestTestTestTest",
  "bild": "test_path_irgendwas"
}

####

POST http://localhost:8080/create/anzeige
Content-Type: application/json

{

    "userId": 1,
    "angges": 1,
    "beschreibung": "TestTestTestTest",
    "preis": 300,
    "start": "Gießen",
    "ziel": "Hamburg",
    "personen": 4,
    "ladeflaeche": 0,
    "ladungsgewicht": 0,
    "ladehoehe": 0

}

####
GET http://localhost:8080/anzeige
Content-Type: application/json